/**
 * Data Module - Cluster Based Theme Ontology
 * Corrected mapping between internal and external themes
 */

const INTERNAL_AUDITS = [

    {
        id: "IA-EMQ-2024-011",
        title: "Global System Audit – External Manufacturing Quality",
        document_path: "data/internal/global_system_audit_emq.pdf",
        themes: [
            "Desktop Audit Overuse",
            "CMO Oversight Gap",
            "Supplier Qualification Weakness",
            "Vendor Audit Frequency Gap",
            "Supplier Risk Visibility Gap",
            "Vendor Documentation Completeness Gap",
            "Supplier Quality Agreement Gap",
            "API Source Verification Gap"
        ],
        summary: "Corporate audit identified systemic over-reliance on desktop audits and limited verification of contract manufacturing organizations.",
        personaSummaries: {
            qc_operations: "Supplier qualification gaps and weak oversight of contract manufacturers may impact reliability of analytical testing and batch release decisions. QC teams should ensure certificates of analysis from suppliers are supported by validated analytical methods and verified testing data.",
            stability_labs: "Supplier oversight weaknesses could affect the reliability of stability data generated by external manufacturers. Stability teams should ensure that stability protocols, data trending, and raw datasets from contract manufacturers are reviewed to confirm shelf-life claims.",
            npi: "The audit indicates potential readiness risks when transferring new products to contract manufacturers. NPI teams should ensure process validation documentation, supplier qualification, and quality agreements are completed before product transfer.",
            regional_quality: "Systemic weaknesses in supplier oversight may create regulatory exposure across multiple manufacturing regions. Regional quality leaders should standardize supplier governance and ensure contract manufacturing oversight is implemented consistently across sites.",
            external_labs: "Reliance on third-party laboratories without verification of raw analytical data creates risks for testing reliability. Oversight should include validation of analytical methods, verification of raw data, and routine compliance checks for external labs.",
            supplier_risk: "The audit highlights elevated supplier risk due to reliance on documentation rather than verified quality data. Supplier risk teams should implement stronger qualification processes, risk scoring, and on-site audits for high-risk suppliers."
        },
        recommendations: [
            "Mandate physical supplier audits",
            "Strengthen vendor oversight program",
            "Implement supplier risk scoring",
            "Improve vendor documentation review"
        ]
    },

    {
        id: "IA-LATINA-2024-044",
        title: "Site Audit – Latina Sterile Operations",
        document_path: "data/internal/site_audit_latina_italy.pdf",
        themes: [
            "Media Fill Contamination",
            "Aseptic Intervention Risk",
            "Environmental Monitoring Excursion",
            "Sterility Investigation Weakness",
            "Aseptic Operator Handling Risk",
            "Cleanroom Classification Failure",
            "Particulate Monitoring Gap",
            "Aseptic Process Validation Gap"
        ],
        summary: "Sterile manufacturing audit identified media fill contamination events and environmental monitoring excursions.",
        personaSummaries: {
            qc_operations: "Media fill contamination events and environmental monitoring excursions indicate weaknesses in microbial testing and investigation practices. QC teams should ensure contamination events trigger thorough laboratory investigations and microbial trend analysis.",
            stability_labs: "Contamination risks in sterile manufacturing could impact stability of affected batches. Stability teams should monitor impacted products for microbial growth and ensure stability samples are closely evaluated for deviations over time.",
            npi: "Media fill failures and aseptic control gaps suggest that sterile manufacturing processes may not yet be ready for new product introduction. NPI teams should confirm that aseptic process validation and contamination controls are completed before launch.",
            regional_quality: "Sterility assurance weaknesses and environmental monitoring excursions may indicate systemic contamination control risks. Regional quality leaders should ensure contamination investigation procedures and environmental monitoring practices are standardized across sites.",
            external_labs: "External microbiology labs supporting environmental monitoring should be reviewed for testing accuracy and validated microbiological methods. Data from these labs should be verified before being used in contamination investigations.",
            supplier_risk: "Although primarily a site issue, contamination risks could also originate from suppliers of sterile components or materials. Supplier risk teams should review sterility controls and supplier quality systems for vendors providing sterile materials."
        },
        recommendations: [
            "Improve contamination investigation procedures",
            "Strengthen aseptic operator training",
            "Implement enhanced monitoring protocols"
        ]
    },

    {
        id: "IA-BRASSICA-2023-112",
        title: "Supplier Audit – Brassica Pharma",
        document_path: "data/internal/supplier_audit_brassica_pharma.pdf",
        themes: [
            "Aseptic Validation Documentation Gap",
            "Raw Data Transparency Issue",
            "Supplier Self Assessment Reliance",
            "Third Party Laboratory Dependence",
            "Supplier Validation Weakness",
            "Vendor Documentation Completeness Gap",
            "Supplier Quality Data Gap"
        ],
        summary: "Supplier qualification relied heavily on documentation review without verifying raw validation data.",
        personaSummaries: {
            qc_operations: "Limited access to raw validation and analytical data from the supplier introduces risks for laboratory verification of product quality. QC teams should require complete analytical datasets and confirm validation of supplier testing methods.",
            stability_labs: "Stability data from the supplier was provided primarily as summarized reports rather than raw datasets. Stability teams should request complete stability data and trending analysis to verify product shelf-life claims.",
            npi: "Supplier validation documentation gaps may delay readiness for product transfers to this manufacturer. NPI teams should verify supplier process validation, analytical methods, and quality systems before introducing new products.",
            regional_quality: "Supplier qualification weaknesses identified in the audit may expose manufacturing operations to regulatory risks across regions. Regional quality leaders should ensure supplier audit standards and qualification criteria are consistently applied.",
            external_labs: "The supplier's reliance on third-party laboratories increases the importance of verifying analytical data integrity. Oversight should ensure these laboratories follow validated methods and maintain regulatory compliance.",
            supplier_risk: "The audit highlights significant supplier risk due to reliance on documentation rather than verified quality data. Supplier risk management should conduct on-site audits, strengthen qualification processes, and ensure quality agreements are enforced."
        },
        recommendations: [
            "Require raw validation datasets",
            "Conduct onsite supplier verification",
            "Implement supplier data integrity checks"
        ]
    },

    {
        id: "IA-FORT-2023-219",
        title: "Site Audit – Fort Washington",
        document_path: "data/internal/site_audit_fort_washington.pdf",
        themes: [
            "OOS Retesting Practice",
            "OOS Investigation Weakness",
            "DEG Testing Waiver",
            "Benzene Testing Waiver",
            "COA Reliance Without Verification",
            "Impurity Testing Gap",
            "Laboratory Control Weakness",
            "Analytical Method Validation Gap"
        ],
        summary: "Audit identified repeated OOS retesting practices and inadequate impurity testing verification.",
        personaSummaries: {
            qc_operations: "Repeated OOS retesting without documented root cause analysis and reliance on supplier COAs without verification indicate weaknesses in laboratory control practices. QC teams should enforce stricter OOS investigation protocols and confirm impurity testing through independent verification.",
            stability_labs: "Impurity testing gaps and weak OOS investigation procedures may compromise the reliability of stability results. Stability teams should ensure impurity levels are monitored during stability studies and investigate deviations thoroughly.",
            npi: "Analytical validation gaps and investigation weaknesses could delay readiness for new product introductions. NPI teams should ensure analytical methods and laboratory investigation procedures are fully validated prior to manufacturing scale-up.",
            regional_quality: "Laboratory control weaknesses identified in the audit could lead to regulatory scrutiny for the site. Regional quality leadership should ensure investigation procedures and impurity testing standards are consistently implemented across facilities.",
            external_labs: "If external laboratories support impurity testing, their analytical methods and data integrity controls must be verified. External lab oversight should include routine audits and validation of analytical procedures.",
            supplier_risk: "Reliance on supplier certificates of analysis without confirmatory testing suggests elevated supplier quality risk. Supplier risk teams should verify supplier testing capabilities and require confirmatory testing for critical materials."
        },
        recommendations: [
            "Reinstate confirmatory impurity testing",
            "Strengthen investigation protocols",
            "Improve laboratory oversight"
        ]
    },

    {
        id: "IA-ENG-2023-088",
        title: "Global Engineering Review – Water Systems",
        document_path: "data/internal/global_engineering_review_water_systems.pdf",
        themes: [
            "Sanitization Postponement",
            "Biofilm Formation Risk",
            "Burkholderia Detection",
            "Water System Microbial Drift",
            "Maintenance Deferral Risk",
            "Water System Design Flaw",
            "Microbial Alert Level Exceedance"
        ],
        summary: "Engineering review identified water system microbial drift and deferred sanitization creating contamination risks.",
        personaSummaries: {
            qc_operations: "Microbial drift and Burkholderia detection in water systems may impact microbial testing and product testing reliability. QC teams should monitor microbial trends closely and investigate contamination events promptly.",
            stability_labs: "Water system contamination risks could affect product stability if contaminated water is used in manufacturing processes. Stability teams should monitor affected product batches for microbial growth or degradation during stability studies.",
            npi: "Water system design flaws and sanitization delays may impact facility readiness for manufacturing new products. NPI teams should ensure utilities such as purified water systems are validated before introducing new manufacturing processes.",
            regional_quality: "Engineering issues affecting water systems could create regulatory compliance risks across multiple sites. Regional quality leaders should ensure water system validation and maintenance programs are standardized.",
            external_labs: "External laboratories involved in microbial testing of water systems should be reviewed to ensure validated testing methods and reliable contamination detection capabilities.",
            supplier_risk: "Suppliers providing water system equipment or maintenance services may contribute to contamination risks. Supplier risk teams should review supplier performance and ensure vendors meet quality standards."
        },
        recommendations: [
            "Implement early microbial warning thresholds",
            "Improve sanitization scheduling",
            "Conduct water system design review"
        ]
    }

];


const EXTERNAL_DOCUMENTS = [

    {
        id: "WL-ACME-2025",
        company: "Acme United Corp",
        document_path: "data/external/acme_united_corp_10_10_2025.pdf",
        themes: [
            "Water System Contamination",
            "Burkholderia Cepacia Detection",
            "Inadequate Sanitization Control",
            "Microbial Monitoring Failure",
            "Water System Design Deficiency"
        ],
        summary: "FDA cited contamination in the purified water system due to inadequate sanitization controls.",
        key_findings: [
            "Burkholderia contamination detected",
            "Sanitization program inadequate"
        ]
    },

    {
        id: "WL-ACELLA-2020",
        company: "Acella Pharmaceuticals",
        document_path: "data/external/acella_pharma_08_14_2020.pdf",
        themes: [
            "Data Integrity Failure",
            "Audit Trail Manipulation",
            "Electronic Record Integrity Gap",
            "Laboratory Data Governance Failure"
        ],
        summary: "FDA warning letter cited data integrity failures and manipulation of electronic laboratory records.",
        key_findings: [
            "Audit trails manipulated",
            "Inadequate data governance"
        ]
    },

    {
        id: "WL-ACCUPACK-2024",
        company: "Accupack Midwest",
        document_path: "data/external/accupack_midwest_08_15_2024.pdf",
        themes: [
            "Inadequate Laboratory Controls",
            "Water System Monitoring Failure",
            "Process Validation Failure",
            "Manufacturing Control Failure"
        ],
        summary: "FDA cited inadequate laboratory and manufacturing controls including water monitoring failures.",
        key_findings: [
            "Laboratory controls insufficient",
            "Process validation incomplete"
        ]
    },

    {
        id: "WL-ACCUBIO-2022",
        company: "Accu Bio Laboratories",
        document_path: "data/external/accu_bio_laboratories_02_24_2022.pdf",
        themes: [
            "OOS Investigation Failure",
            "OOS Retesting Violations",
            "Laboratory Investigation Weakness",
            "Analytical Method Validation Gap"
        ],
        summary: "FDA warning letter cited systemic failures in OOS investigation procedures.",
        key_findings: [
            "OOS results invalidated through retesting"
        ]
    },

    {
        id: "WL-ACCRAPAC-2023",
        company: "Accra Pac",
        document_path: "data/external/accra_pac_04_20_2023.pdf",
        themes: [
            "Benzene Contamination",
            "Propellant Impurity Failure",
            "Raw Material Testing Failure",
            "Supplier Qualification Failure"
        ],
        summary: "FDA cited benzene contamination caused by inadequate propellant testing.",
        key_findings: [
            "Benzene detected in product batches"
        ]
    },

    {
        id: "WL-ABSARA-2021",
        company: "Absara Cosmetics",
        document_path: "data/external/absara_cosmetics_02_18_2021.pdf",
        themes: [
            "Subpotent Drug Product",
            "Product Quality Failure",
            "Inadequate Test Methods",
            "Finished Product Testing Gap"
        ],
        summary: "FDA warning letter cited subpotent product due to inadequate test methods.",
        key_findings: [
            "Finished product potency below specification"
        ]
    },

    {
        id: "WL-ABRAXIS-2022",
        company: "Abraxis Bioscience",
        document_path: "data/external/abraxis_bioscience_llc_10_31_2022.pdf",
        themes: [
            "Media Fill Failure",
            "Aseptic Technique Deficiency",
            "Sterility Assurance Breakdown",
            "Aseptic Process Validation Gap"
        ],
        summary: "FDA cited repeated media fill failures and sterility assurance issues.",
        key_findings: [
            "Media fill contamination events observed"
        ]
    },

    {
        id: "WL-AACE-2025",
        company: "AACE Pharmaceuticals",
        document_path: "data/external/aace_pharmaceuticals_05_13_2025.pdf",
        themes: [
            "Supplier Qualification Failure",
            "CMO Oversight Failure",
            "Contract Manufacturing Compliance Gap"
        ],
        summary: "FDA warning letter cited inadequate oversight of contract manufacturer Brassica Pharma.",
        key_findings: [
            "Supplier oversight inadequate"
        ]
    }

];



const THEME_CLUSTERS = [

    {
        cluster_id: "cluster_water",
        parent_category: "Water System Contamination",
        similarity_score: 0.93,
        similarity_reason: "Internal engineering review identified Burkholderia detection and sanitization postponement while FDA cited water system contamination and inadequate sanitization controls.",
        themes: [
            "Sanitization Postponement",
            "Biofilm Formation Risk",
            "Burkholderia Detection",
            "Water System Contamination",
            "Burkholderia Cepacia Detection",
            "Inadequate Sanitization Control"
        ],
        internal_docs: ["IA-ENG-2023-088"],
        external_docs: ["WL-ACME-2025", "WL-ACCUPACK-2024"]
    },

    {
        cluster_id: "cluster_oos",
        parent_category: "OOS Investigation Failure",
        similarity_score: 0.91,
        similarity_reason: "Internal audit cited OOS retesting practices while FDA warning letters cited nearly identical failures involving invalid OOS investigations.",
        themes: [
            "OOS Retesting Practice",
            "OOS Investigation Weakness",
            "OOS Investigation Failure",
            "OOS Retesting Violations"
        ],
        internal_docs: ["IA-FORT-2023-219"],
        external_docs: ["WL-ACCUBIO-2022"]
    },

    {
        cluster_id: "cluster_sterility",
        parent_category: "Sterility Assurance Failure",
        similarity_score: 0.92,
        similarity_reason: "Internal sterile manufacturing audit identified media fill contamination and aseptic handling risks while FDA warning letters cited media fill failures.",
        themes: [
            "Media Fill Contamination",
            "Aseptic Intervention Risk",
            "Media Fill Failure",
            "Aseptic Technique Deficiency",
            "Aseptic Process Validation Gap"
        ],
        internal_docs: ["IA-LATINA-2024-044"],
        external_docs: ["WL-ABRAXIS-2022"]
    },

    {
        cluster_id: "cluster_supplier",
        parent_category: "Supplier Oversight Deficiency",
        similarity_score: 0.89,
        similarity_reason: "Internal supplier audits identified reliance on documentation and lack of vendor oversight which aligns with FDA warning letters citing supplier qualification failures.",
        themes: [
            "Supplier Qualification Weakness",
            "Supplier Self Assessment Reliance",
            "Vendor Documentation Completeness Gap",
            "Supplier Qualification Failure",
            "CMO Oversight Failure"
        ],
        internal_docs: ["IA-BRASSICA-2023-112", "IA-EMQ-2024-011"],
        external_docs: ["WL-AACE-2025", "WL-ACCRAPAC-2023"]
    },

    {
        cluster_id: "cluster_impurity",
        parent_category: "Impurity Testing Failure",
        similarity_score: 0.88,
        similarity_reason: "Internal audit identified benzene testing waivers while FDA warning letters cited benzene contamination due to inadequate impurity testing.",
        themes: [
            "Benzene Testing Waiver",
            "Impurity Testing Gap",
            "Benzene Contamination",
            "Propellant Impurity Failure"
        ],
        internal_docs: ["IA-FORT-2023-219"],
        external_docs: ["WL-ACCRAPAC-2023"]
    },

    {
        cluster_id: "cluster_product_quality",
        parent_category: "Product Quality Failure",
        similarity_score: 0.85,
        similarity_reason: "External warning letters cited subpotent product quality failures due to inadequate testing methods.",
        themes: [
            "Subpotent Drug Product",
            "Product Quality Failure",
            "Finished Product Testing Gap"
        ],
        internal_docs: ["IA-FORT-2023-219"],
        external_docs: ["WL-ABSARA-2021"]
    }

];

/**
 * Persona Definitions - Quality Function Personas
 * Each persona has specific focus areas for summary framing
 */
const QUALITY_PERSONAS = {
    'SCQ': {
        label: 'SCQ',
        personas: [
            {
                id: 'qc_operations',
                name: 'QC Operations',
                focusAreas: ['laboratory controls', 'OOS investigations', 'analytical testing', 'data integrity'],
                keywords: ['laboratory', 'testing', 'OOS', 'analytical', 'data integrity', 'QC', 'quality control', 'investigation', 'test method', 'specification']
            },
            {
                id: 'stability_labs',
                name: 'Stability Labs',
                focusAreas: ['stability programs', 'shelf life', 'stability testing protocols', 'out-of-trend stability results'],
                keywords: ['stability', 'shelf life', 'storage', 'degradation', 'out-of-trend', 'OOT', 'stability study', 'expiry', 'retest']
            }
        ]
    },
    'CQ': {
        label: 'CQ',
        personas: [
            {
                id: 'npi',
                name: 'NPI',
                focusAreas: ['process readiness', 'validation readiness', 'manufacturing transfer', 'regulatory readiness'],
                keywords: ['validation', 'process', 'transfer', 'scale-up', 'NPI', 'new product', 'manufacturing readiness', 'tech transfer', 'process validation']
            },
            {
                id: 'regional_quality',
                name: 'Regional Quality',
                focusAreas: ['regional compliance', 'regulatory inspections', 'cross-site quality governance'],
                keywords: ['regional', 'site', 'inspection', 'compliance', 'governance', 'multi-site', 'cross-site', 'regulatory', 'audit']
            }
        ]
    },
    'EQ': {
        label: 'EQ',
        personas: [
            {
                id: 'external_labs',
                name: 'External Labs',
                focusAreas: ['third-party laboratory oversight', 'testing method compliance', 'external data reliability'],
                keywords: ['external lab', 'third-party', 'contract lab', 'outsourced testing', 'external testing', 'laboratory oversight', 'vendor lab']
            },
            {
                id: 'supplier_risk',
                name: 'Supplier Risk Management',
                focusAreas: ['supplier qualification', 'vendor risk', 'supplier audits', 'raw material quality risks'],
                keywords: ['supplier', 'vendor', 'CMO', 'contract manufacturer', 'raw material', 'API', 'supplier audit', 'qualification', 'supplier risk']
            }
        ]
    }
};

// Default persona (no persona selected)
let currentPersona = null;

/**
 * Get all personas as a flat array
 */
function getAllPersonas() {
    const allPersonas = [];
    Object.keys(QUALITY_PERSONAS).forEach(category => {
        QUALITY_PERSONAS[category].personas.forEach(persona => {
            allPersonas.push({
                ...persona,
                category: category
            });
        });
    });
    return allPersonas;
}

/**
 * Get persona by ID
 */
function getPersonaById(personaId) {
    const allPersonas = getAllPersonas();
    return allPersonas.find(p => p.id === personaId);
}